birds = []
birds.append("ring-billed gull")
birds.append("canadian goose")
birds.append("common goldeneye")
birds.append("hooded merganser")
birds.append("cooper's hawk")
birds.append("downy woodpecker")
birds.append("black-capped chickadee")
birds.append("american robin")
birds.append("mallard")
print(birds)
birds.insert(0, "common merganser")
print(birds)
del birds[0]
print(birds)
del birds[1]
print(birds)
birds.insert(1, "canadian goose")
birds.insert(0, "northern cardinal")
print(birds)
del birds[0]
print(birds)
birds.insert(3, "bald eagle")
print(birds)
not_seen = birds.pop(3)
print("I didn't see a " + not_seen + ".")
birds.append("sandhill crane")
also_not_seen = birds.pop()
print("I also didn't see a " + also_not_seen + ".")
birds.insert(5, "belted kingfisher")
birds.insert(2, "cackling goose")
print(birds)
birds.remove("belted kingfisher")
birds.remove("cackling goose")
print(birds)
print(sorted(birds))
print(sorted(birds, reverse=True))
birds.sort()
print(birds)
birds.sort(reverse=True)
print(birds)
birds.reverse()
print(birds)
birds.reverse()
print(birds)
print(len(birds))
message = "I saw " + str(len(birds)) + " birds at Jackson Park yesterday."
print(message)