world_places = ["New Zealand", "Great Britain", "Australia", "India", "Spain"]
print(world_places)
print(sorted(world_places))
print(world_places)
print(sorted(world_places, reverse=True))
print(world_places)
world_places.reverse()
print(world_places)
world_places.reverse()
print(world_places)
world_places.sort()
print(world_places)
world_places.sort(reverse=True)
print(world_places)